### ISSUE TITLE
在与SharpPluginLoader一起使用时会发生报错

### ISSUE THREAD

**Issue by Ecamika** [eigeen/LuaFramework#1]
![{85061D00-A8F9-46F3-9FAF-0EC41E91A2DD}](https://github.com/user-attachments/assets/7024f8cc-2724-4056-9d1a-0e015d3bfc37)
```
[ 13:11:34 ] [lua-framework] Hook Error: cannot find address of Failed to get address of MessageSent: memory module error: pattern not found
```
移除[SharpPluginLoader](https://github.com/Fexty12573/SharpPluginLoader)插件后不会报错

**Comment by eigeen** [comment]
目前发现，当SPL安装后，所有stracker's loader的插件都无法扫描到特征码。这可能是由于SPL对游戏加载流程的破坏性更改导致的。由于初始加载时无法找到任何函数，进而也无法寻找到稳定的策略做延迟加载，目前暂时处于无解状态。

**Comment by Ecamika** [comment]
T-T

**Comment by eigeen** [comment]
据我所知大部分人用spl是为了解锁联机区域mod。如果你有需要的少数mod，开源的，我可以迁移到lua实现（下版本将支持游戏内imgui）
